const countries = {
  "en-GB": "English",
  "en-US": "English",
  "hi-IN": "Hindi",
  "fr-FR": "French",
  "de-DE": "German",
  "es-ES": "Spanish",
  "it-IT": "Italian",
  "ja-JP": "Japanese",
  "ko-KR": "Korean",
  "zh-CN": "Chinese (Simplified)",
  "zh-TW": "Chinese (Traditional)",
  "ru-RU": "Russian",
  "ar-SA": "Arabic",
  "pt-PT": "Portuguese",
  "pt-BR": "Portuguese (Brazil)",
  "nl-NL": "Dutch",
  "sv-SE": "Swedish",
  "no-NO": "Norwegian",
  "fi-FI": "Finnish",
  "da-DK": "Danish",
  "pl-PL": "Polish",
  "tr-TR": "Turkish",
  "el-GR": "Greek",
  "he-IL": "Hebrew",
  "th-TH": "Thai",
  "vi-VN": "Vietnamese",
  "id-ID": "Indonesian",
  "ms-MY": "Malay",
  "fa-IR": "Persian",
  "uk-UA": "Ukrainian",
  "cs-CZ": "Czech",
  "hu-HU": "Hungarian",
  "ro-RO": "Romanian",
  "sk-SK": "Slovak",
  "bg-BG": "Bulgarian",
  "hr-HR": "Croatian",
  "sr-RS": "Serbian",
  "sl-SI": "Slovenian",
  "et-EE": "Estonian",
  "lv-LV": "Latvian",
  "lt-LT": "Lithuanian",
  "is-IS": "Icelandic",
  "ga-IE": "Irish",
  "mt-MT": "Maltese",
  "cy-GB": "Welsh",
  "eu-ES": "Basque",
  "ca-ES": "Catalan",
  "gl-ES": "Galician"
};